import { StyleSheet } from 'react-native';
import { colors, shadows, spacing, typography } from '@/styles/tokens';

export const bloomStyles = StyleSheet.create({
  topBar: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.xs },
  backButton: { alignItems: 'center', backgroundColor: colors.card, borderColor: colors.line, borderRadius: 18, borderWidth: 1, height: 36, justifyContent: 'center', width: 36 },
  topBarTitle: { color: colors.ink, flex: 1, fontFamily: typography.display, fontSize: 21 },
  bloomBadge: { backgroundColor: colors.sageLight, borderRadius: 999, color: colors.sageDark, fontFamily: typography.uiBold, fontSize: 10, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  header: { paddingBottom: spacing.lg },
  headerRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  headerCopy: { flex: 1 },
  filterButton: { alignItems: 'center', backgroundColor: colors.card, borderColor: colors.line, borderRadius: 14, borderWidth: 1, flexDirection: 'row', gap: 4, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  filterButtonText: { color: colors.ink, fontFamily: typography.uiBold, fontSize: 12 },
  filterChips: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', gap: spacing.xs, marginTop: spacing.sm },
  filterChip: { alignItems: 'center', backgroundColor: colors.sageLight, borderRadius: 999, flexDirection: 'row', gap: 4, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  filterChipText: { color: colors.sageDark, fontFamily: typography.uiBold, fontSize: 11 },
  filterReset: { paddingHorizontal: spacing.xs, paddingVertical: spacing.xs },
  filterResetText: { color: colors.coralDark, fontFamily: typography.uiBold, fontSize: 11 },
  eyebrow: { color: colors.sageDark, fontSize: 11, fontWeight: '800', letterSpacing: 2 },
  title: { color: colors.ink, fontFamily: typography.display, fontSize: 29, marginTop: spacing.sm },
  subtitle: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 13, lineHeight: 19, marginTop: spacing.sm },
  loading: { alignItems: 'center', flex: 1, justifyContent: 'center' },
  error: { color: colors.coralDark, fontSize: 13, lineHeight: 19, paddingVertical: spacing.lg },
  empty: { color: colors.inkSoft, fontSize: 14, lineHeight: 21, paddingVertical: spacing.xl },
  listContent: { paddingBottom: spacing.xl },
  loadMoreFooter: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, justifyContent: 'center', paddingVertical: spacing.lg },
  loadMoreText: { color: colors.inkSoft, fontSize: 12 },
  timelineEnd: { color: colors.inkSoft, fontSize: 12, paddingBottom: spacing.xl, paddingTop: spacing.lg, textAlign: 'center' },
  card: { ...shadows.card, backgroundColor: colors.card, borderColor: colors.line, borderRadius: 20, borderWidth: 1, marginBottom: spacing.md, padding: spacing.lg, position: 'relative' },
  cardOpen: { elevation: 10, zIndex: 10 },
  cardPressed: { opacity: 0.86 },
  authorRow: { alignItems: 'center', flexDirection: 'row' },
  avatar: { alignItems: 'center', backgroundColor: colors.sageLight, borderRadius: 20, height: 40, justifyContent: 'center', marginRight: spacing.sm, width: 40 },
  avatarText: { color: colors.sageDark, fontSize: 16, fontWeight: '800' },
  authorCopy: { flex: 1 },
  author: { color: colors.ink, fontFamily: typography.uiBold, fontSize: 14 },
  date: { color: colors.inkSoft, fontSize: 11, marginTop: 2 },
  mood: { backgroundColor: colors.lavenderLight, borderRadius: 12, color: colors.sageDark, fontSize: 10, fontWeight: '700', paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  body: { color: colors.ink, fontFamily: typography.ui, fontSize: 15, lineHeight: 23, marginTop: spacing.lg },
  mediaGallery: { marginTop: spacing.md },
  media: { borderRadius: 16, height: 220, marginRight: spacing.sm, width: 300 },
  actionRow: { alignItems: 'center', borderTopColor: colors.line, borderTopWidth: 1, flexDirection: 'row', gap: spacing.md, marginTop: spacing.lg, paddingTop: spacing.md },
  reaction: { alignItems: 'center', backgroundColor: colors.background, borderRadius: 14, flexDirection: 'row', gap: 4, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  reactionActive: { backgroundColor: colors.cardWarm },
  reactionText: { fontSize: 16 },
  reactionCount: { color: colors.inkSoft, fontSize: 12, fontWeight: '700' },
  reactionPicker: { alignItems: 'center', backgroundColor: colors.card, borderColor: colors.line, borderRadius: 18, borderWidth: 1, bottom: 52, flexDirection: 'row', gap: spacing.sm, left: spacing.lg, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs, position: 'absolute', zIndex: 20, ...shadows.card, elevation: 12 },
  reactionOption: { alignItems: 'center', borderRadius: 16, height: 32, justifyContent: 'center', width: 32 },
  reactionOptionText: { fontSize: 21 },
  commentAction: { color: colors.inkSoft, fontSize: 12, fontWeight: '700' },
  comments: { borderTopColor: colors.line, borderTopWidth: 1, marginTop: spacing.md, paddingTop: spacing.md },
  comment: { marginBottom: spacing.sm },
  commentAuthor: { color: colors.ink, fontSize: 12, fontWeight: '700' },
  commentBody: { color: colors.inkSoft, fontSize: 13, lineHeight: 18, marginTop: 2 },
  commentInputRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, marginTop: spacing.sm },
  commentInput: { borderColor: colors.line, borderRadius: 14, borderWidth: 1, color: colors.ink, flex: 1, fontSize: 13, minHeight: 38, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  commentSend: { color: colors.coralDark, fontSize: 12, fontWeight: '800' },
  dayDivider: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.sm, marginTop: spacing.sm },
  dayDividerLine: { backgroundColor: colors.line, flex: 1, height: 1 },
  dayDividerText: { color: colors.inkSoft, fontFamily: typography.uiBold, fontSize: 10, letterSpacing: 0.8, textTransform: 'uppercase' },
  sheetBackdrop: { backgroundColor: 'rgba(27, 35, 30, 0.35)', flex: 1, justifyContent: 'flex-end' },
  sheet: { backgroundColor: colors.background, borderTopLeftRadius: 28, borderTopRightRadius: 28, maxHeight: '88%', padding: spacing.lg, paddingBottom: spacing.xl },
  sheetHandle: { alignSelf: 'center', backgroundColor: colors.line, borderRadius: 999, height: 4, marginBottom: spacing.md, width: 42 },
  sheetHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.lg },
  sheetTitle: { color: colors.ink, fontFamily: typography.display, fontSize: 24 },
  sheetClose: { alignItems: 'center', backgroundColor: colors.card, borderRadius: 18, height: 34, justifyContent: 'center', width: 34 },
  filterSectionTitle: { color: colors.ink, fontFamily: typography.uiBold, fontSize: 13, marginBottom: spacing.sm, marginTop: spacing.sm },
  filterDateRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm },
  filterDateButton: { alignItems: 'center', backgroundColor: colors.card, borderColor: colors.line, borderRadius: 14, borderWidth: 1, flex: 1, flexDirection: 'row', gap: spacing.sm, paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  filterDateText: { color: colors.ink, fontFamily: typography.ui, fontSize: 13 },
  filterClearButton: { alignItems: 'center', height: 34, justifyContent: 'center', width: 34 },
  pickerPanel: { alignItems: 'center', backgroundColor: colors.card, borderRadius: 16, marginTop: spacing.sm, overflow: 'hidden' },
  filterMember: { alignItems: 'center', backgroundColor: colors.card, borderColor: colors.line, borderRadius: 14, borderWidth: 1, flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.xs, paddingHorizontal: spacing.sm, paddingVertical: spacing.sm },
  filterMemberSelected: { backgroundColor: colors.sageLight, borderColor: colors.sage },
  filterMemberAvatar: { alignItems: 'center', backgroundColor: colors.lavenderLight, borderRadius: 18, height: 34, justifyContent: 'center', width: 34 },
  filterMemberAvatarText: { color: colors.sageDark, fontFamily: typography.uiBold, fontSize: 13 },
  filterMemberName: { color: colors.ink, flex: 1, fontFamily: typography.ui, fontSize: 13 },
  filterActions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.lg },
  filterResetButton: { alignItems: 'center', borderColor: colors.line, borderRadius: 15, borderWidth: 1, flex: 1, justifyContent: 'center', paddingVertical: spacing.md },
  filterResetButtonText: { color: colors.inkSoft, fontFamily: typography.uiBold, fontSize: 13 },
  filterApplyButton: { alignItems: 'center', backgroundColor: colors.sageDark, borderRadius: 15, flex: 1, justifyContent: 'center', paddingVertical: spacing.md },
  filterApplyButtonText: { color: colors.card, fontFamily: typography.uiBold, fontSize: 13 },
});
