import { StyleSheet } from 'react-native';
import { colors, shadows, spacing, typography } from '@/styles/tokens';

export const bloomStyles = StyleSheet.create({
  topBar: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.xs },
  backButton: { alignItems: 'center', backgroundColor: colors.card, borderColor: colors.line, borderRadius: 18, borderWidth: 1, height: 36, justifyContent: 'center', width: 36 },
  topBarTitle: { color: colors.ink, flex: 1, fontFamily: typography.display, fontSize: 21 },
  bloomBadge: { backgroundColor: colors.sageLight, borderRadius: 999, color: colors.sageDark, fontFamily: typography.uiBold, fontSize: 10, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  header: { paddingBottom: spacing.lg },
  eyebrow: { color: colors.sageDark, fontSize: 11, fontWeight: '800', letterSpacing: 2 },
  title: { color: colors.ink, fontFamily: typography.display, fontSize: 29, marginTop: spacing.sm },
  subtitle: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 13, lineHeight: 19, marginTop: spacing.sm },
  loading: { alignItems: 'center', flex: 1, justifyContent: 'center' },
  error: { color: colors.coralDark, fontSize: 13, lineHeight: 19, paddingVertical: spacing.lg },
  empty: { color: colors.inkSoft, fontSize: 14, lineHeight: 21, paddingVertical: spacing.xl },
  listContent: { paddingBottom: spacing.xl },
  card: { ...shadows.card, backgroundColor: colors.card, borderColor: colors.line, borderRadius: 20, borderWidth: 1, marginBottom: spacing.md, padding: spacing.lg, position: 'relative' },
  cardPressed: { opacity: 0.86 },
  authorRow: { alignItems: 'center', flexDirection: 'row' },
  avatar: { alignItems: 'center', backgroundColor: colors.sageLight, borderRadius: 20, height: 40, justifyContent: 'center', marginRight: spacing.sm, width: 40 },
  avatarText: { color: colors.sageDark, fontSize: 16, fontWeight: '800' },
  authorCopy: { flex: 1 },
  author: { color: colors.ink, fontFamily: typography.uiBold, fontSize: 14 },
  date: { color: colors.inkSoft, fontSize: 11, marginTop: 2 },
  mood: { backgroundColor: colors.lavenderLight, borderRadius: 12, color: colors.sageDark, fontSize: 10, fontWeight: '700', paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  body: { color: colors.ink, fontFamily: typography.ui, fontSize: 15, lineHeight: 23, marginTop: spacing.lg },
  mediaGallery: { marginTop: spacing.md },
  media: { borderRadius: 16, height: 220, marginRight: spacing.sm, width: 300 },
  actionRow: { alignItems: 'center', borderTopColor: colors.line, borderTopWidth: 1, flexDirection: 'row', gap: spacing.md, marginTop: spacing.lg, paddingTop: spacing.md },
  reaction: { alignItems: 'center', backgroundColor: colors.background, borderRadius: 14, flexDirection: 'row', gap: 4, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  reactionActive: { backgroundColor: colors.cardWarm },
  reactionText: { fontSize: 16 },
  reactionCount: { color: colors.inkSoft, fontSize: 12, fontWeight: '700' },
  reactionPicker: { alignItems: 'center', backgroundColor: colors.card, borderColor: colors.line, borderRadius: 18, borderWidth: 1, bottom: 52, flexDirection: 'row', gap: spacing.sm, left: spacing.lg, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs, position: 'absolute', zIndex: 20, ...shadows.card },
  reactionOption: { alignItems: 'center', borderRadius: 16, height: 32, justifyContent: 'center', width: 32 },
  reactionOptionText: { fontSize: 21 },
  commentAction: { color: colors.inkSoft, fontSize: 12, fontWeight: '700' },
  comments: { borderTopColor: colors.line, borderTopWidth: 1, marginTop: spacing.md, paddingTop: spacing.md },
  comment: { marginBottom: spacing.sm },
  commentAuthor: { color: colors.ink, fontSize: 12, fontWeight: '700' },
  commentBody: { color: colors.inkSoft, fontSize: 13, lineHeight: 18, marginTop: 2 },
  commentInputRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, marginTop: spacing.sm },
  commentInput: { borderColor: colors.line, borderRadius: 14, borderWidth: 1, color: colors.ink, flex: 1, fontSize: 13, minHeight: 38, paddingHorizontal: spacing.sm, paddingVertical: spacing.xs },
  commentSend: { color: colors.coralDark, fontSize: 12, fontWeight: '800' },
  dayDivider: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, marginBottom: spacing.sm, marginTop: spacing.sm },
  dayDividerLine: { backgroundColor: colors.line, flex: 1, height: 1 },
  dayDividerText: { color: colors.inkSoft, fontFamily: typography.uiBold, fontSize: 10, letterSpacing: 0.8, textTransform: 'uppercase' },
});
