import { StyleSheet } from 'react-native';
import { colors, shadows, spacing, typography } from '@/styles/tokens';

export const circleDetailStyles = StyleSheet.create({
  topBar: { alignItems: 'center', flexDirection: 'row', marginBottom: spacing.lg },
  backButton: { alignItems: 'center', backgroundColor: colors.card, borderColor: colors.line, borderRadius: 18, borderWidth: 1, height: 36, justifyContent: 'center', width: 36 },
  topBarTitle: { color: colors.ink, flex: 1, fontFamily: typography.uiBold, fontSize: 15, marginHorizontal: spacing.md },
  topBarAction: { alignItems: 'center', backgroundColor: colors.sageLight, borderRadius: 18, height: 36, justifyContent: 'center', width: 36 },
  topBarActionPlaceholder: { height: 36, width: 36 },
  hero: { ...shadows.card, alignItems: 'center', backgroundColor: colors.cardWarm, borderRadius: 24, padding: spacing.xl },
  emoji: { fontSize: 46 },
  emojiGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  emojiOption: { alignItems: 'center', backgroundColor: colors.card, borderColor: colors.line, borderRadius: 14, borderWidth: 1, height: 48, justifyContent: 'center', width: 48 },
  emojiOptionSelected: { backgroundColor: colors.sageLight, borderColor: colors.sageDark },
  emojiOptionText: { fontSize: 25 },
  title: { color: colors.ink, fontFamily: typography.display, fontSize: 26, marginTop: spacing.sm, textAlign: 'center' },
  status: { color: colors.sageDark, fontFamily: typography.uiBold, fontSize: 11, letterSpacing: 2, marginTop: spacing.sm },
  bloomDate: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 13, marginTop: spacing.xs },
  bloomDateValue: { color: colors.ink, fontFamily: typography.uiBold, fontSize: 16, marginTop: spacing.xs },
  heroMeta: { alignItems: 'center', flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'center', marginTop: spacing.md },
  heroMetaText: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 11 },
  heroMetaDot: { color: colors.line, marginHorizontal: spacing.xs },
  progressTrack: { backgroundColor: colors.card, borderRadius: 5, height: 10, marginTop: spacing.lg, overflow: 'hidden', width: '100%' },
  progressFill: { backgroundColor: colors.sage, borderRadius: 5, height: '100%' },
  progressLabel: { color: colors.sageDark, fontFamily: typography.uiBold, fontSize: 12, marginTop: spacing.sm },
  section: { color: colors.inkSoft, fontFamily: typography.uiBold, fontSize: 12, letterSpacing: 1, marginTop: spacing.xl, textTransform: 'uppercase' },
  member: { ...shadows.card, alignItems: 'center', backgroundColor: colors.card, borderColor: colors.line, borderRadius: 16, borderWidth: 1, flexDirection: 'row', marginTop: spacing.sm, padding: spacing.md },
  avatar: { alignItems: 'center', backgroundColor: colors.sageLight, borderRadius: 18, height: 36, justifyContent: 'center', marginRight: spacing.sm, width: 36 },
  avatarImage: { borderRadius: 18, height: 36, width: 36 },
  avatarText: { color: colors.sageDark, fontFamily: typography.uiBold, fontSize: 14 },
  memberCopy: { flex: 1 },
  removeMemberButton: { alignItems: 'center', backgroundColor: '#FFF3F1', borderRadius: 16, height: 32, justifyContent: 'center', width: 32 },
  memberName: { color: colors.ink, fontFamily: typography.uiBold, fontSize: 14 },
  memberMeta: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 11, marginTop: 2 },
  form: { backgroundColor: colors.lavenderLight, borderRadius: 18, marginTop: spacing.md, padding: spacing.md },
  input: { backgroundColor: colors.card, borderColor: colors.line, borderRadius: 12, borderWidth: 1, color: colors.ink, fontFamily: typography.ui, fontSize: 14, paddingHorizontal: spacing.md, paddingVertical: spacing.sm },
  inviteButton: { alignItems: 'center', backgroundColor: colors.sageDark, borderRadius: 12, marginTop: spacing.sm, minHeight: 42, justifyContent: 'center' },
  inviteButtonText: { color: colors.card, fontFamily: typography.uiBold, fontSize: 13 },
  action: { alignItems: 'center', backgroundColor: colors.coral, borderRadius: 15, marginTop: spacing.xl, minHeight: 50, justifyContent: 'center' },
  actionText: { color: colors.card, fontFamily: typography.uiBold, fontSize: 14 },
  secondaryAction: { alignItems: 'center', backgroundColor: colors.sageLight, borderRadius: 15, flexDirection: 'row', gap: spacing.sm, marginTop: spacing.md, minHeight: 50, justifyContent: 'center' },
  secondaryActionText: { color: colors.sageDark, fontFamily: typography.uiBold, fontSize: 14 },
  danger: { alignItems: 'center', borderColor: colors.coralDark, borderRadius: 15, borderWidth: 1, marginTop: spacing.md, minHeight: 50, justifyContent: 'center' },
  dangerText: { color: colors.coralDark, fontFamily: typography.uiBold, fontSize: 14 },
  loading: { alignItems: 'center', flex: 1, justifyContent: 'center' },
  error: { color: colors.coralDark, fontFamily: typography.ui, fontSize: 13, lineHeight: 20, marginTop: spacing.lg },
  sheetBackdrop: { backgroundColor: 'rgba(51,38,46,0.35)', flex: 1, justifyContent: 'flex-end' },
  sheet: { backgroundColor: colors.background, borderTopLeftRadius: 28, borderTopRightRadius: 28, maxHeight: "88%", padding: spacing.xl, paddingBottom: 34 },
  sheetHandle: { alignSelf: 'center', backgroundColor: colors.line, borderRadius: 4, height: 5, marginBottom: spacing.lg, width: 42 },
  sheetHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.lg },
  sheetTitle: { color: colors.ink, fontFamily: typography.display, fontSize: 22 },
  sheetClose: { color: colors.inkSoft, fontSize: 30, fontWeight: '300', lineHeight: 30 },
  label: { color: colors.inkSoft, fontFamily: typography.uiBold, fontSize: 12, letterSpacing: 1, marginBottom: spacing.xs, marginTop: spacing.md, textTransform: 'uppercase' },
  bloomPickerRow: { flexDirection: 'row', gap: spacing.sm },
  bloomPickerButton: { backgroundColor: colors.card, borderColor: colors.line, borderRadius: 12, borderWidth: 1, flex: 1, padding: spacing.sm },
  bloomPickerLabel: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 11 },
  bloomPickerValue: { color: colors.ink, fontFamily: typography.uiBold, fontSize: 13, marginTop: 2 },
  pickerPanel: { alignItems: 'center', backgroundColor: colors.cardWarm, borderRadius: 16, marginTop: spacing.sm, padding: spacing.sm },
  pickerDone: { alignSelf: 'stretch', alignItems: 'center', backgroundColor: colors.sageLight, borderRadius: 10, marginTop: spacing.xs, padding: spacing.sm },
  pickerDoneText: { color: colors.sageDark, fontFamily: typography.uiBold, fontSize: 13 },
  saveButton: { alignItems: 'center', backgroundColor: colors.coral, borderRadius: 15, justifyContent: 'center', marginTop: spacing.xl, minHeight: 50 },
  saveButtonDisabled: { opacity: 0.6 },
  saveButtonText: { color: colors.card, fontFamily: typography.uiBold, fontSize: 14 },
  confirmBody: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 14, lineHeight: 21 },
  deleteButton: { alignItems: 'center', backgroundColor: colors.coralDark, borderRadius: 15, justifyContent: 'center', marginTop: spacing.xl, minHeight: 50 },
  deleteButtonText: { color: colors.card, fontFamily: typography.uiBold, fontSize: 14 },
});
