import { StyleSheet } from "react-native";
import { colors, shadows, spacing, typography } from "@/styles/tokens";

export const entryDetailStyles = StyleSheet.create({
  detailLayout: { flex: 1 },
  detailScroll: { flex: 1, marginRight: -spacing.xl },
  detailScrollContent: { paddingBottom: spacing.md, paddingRight: spacing.xl },
  composerDock: {
    backgroundColor: colors.background,
    borderTopColor: colors.line,
    borderTopWidth: 1,
    paddingTop: spacing.sm,
  },
  topBar: {
    alignItems: "center",
    flexDirection: "row",
    gap: spacing.sm,
    marginBottom: spacing.lg,
  },
  backButton: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  backIcon: { color: colors.ink, fontSize: 18, fontWeight: "700" },
  title: {
    color: colors.ink,
    flex: 1,
    fontFamily: typography.display,
    fontSize: 22,
  },
  loading: { alignItems: "center", flex: 1, justifyContent: "center" },
  card: {
    ...shadows.card,
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 20,
    borderWidth: 1,
    padding: spacing.lg,
    position: "relative",
  },
  cardOpen: { elevation: 10, zIndex: 10 },
  authorRow: { alignItems: "center", flexDirection: "row", gap: spacing.sm },
  avatar: {
    alignItems: "center",
    backgroundColor: colors.sageLight,
    borderRadius: 20,
    height: 40,
    justifyContent: "center",
    width: 40,
  },
  avatarImage: { borderRadius: 20, height: 40, width: 40 },
  avatarText: { color: colors.sageDark, fontFamily: typography.uiBold, fontSize: 16 },
  authorCopy: { flex: 1 },
  author: { color: colors.ink, fontFamily: typography.uiBold, fontSize: 14 },
  when: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 11, marginTop: 2 },
  mood: {
    backgroundColor: colors.lavenderLight,
    borderRadius: 999,
    color: colors.sageDark,
    fontFamily: typography.uiBold,
    fontSize: 11,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  body: {
    color: colors.ink,
    fontFamily: typography.ui,
    fontSize: 15,
    lineHeight: 24,
    marginTop: spacing.lg,
  },
  mediaGallery: { marginTop: spacing.lg },
  media: { borderRadius: 16, height: 220, marginRight: spacing.sm, width: 320 },
  reactions: { flexDirection: "row", gap: spacing.sm, marginTop: spacing.lg },
  reaction: {
    alignItems: "center",
    backgroundColor: colors.background,
    borderRadius: 999,
    flexDirection: "row",
    gap: 4,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
  },
  reactionActive: { backgroundColor: colors.cardWarm },
  reactionPicker: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 18,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    bottom: 52,
    left: spacing.lg,
    position: "absolute",
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.xs,
    zIndex: 20,
    ...shadows.card,
    elevation: 12,
  },
  reactionOption: {
    alignItems: "center",
    borderRadius: 16,
    height: 32,
    justifyContent: "center",
    width: 32,
  },
  reactionOptionText: { fontSize: 21 },
  reactionText: { fontSize: 16 },
  reactionCount: { color: colors.inkSoft, fontFamily: typography.uiBold, fontSize: 12 },
  sectionLabel: {
    color: colors.inkSoft,
    fontFamily: typography.uiBold,
    fontSize: 11,
    letterSpacing: 1,
    marginBottom: spacing.md,
    textTransform: "uppercase",
  },
  commentsSection: {
    borderTopColor: colors.line,
    borderTopWidth: 1,
    marginTop: spacing.xl,
    padding: spacing.lg,
  },
  noComments: {
    color: colors.inkSoft,
    fontFamily: typography.ui,
    fontSize: 13,
    lineHeight: 20,
    marginBottom: spacing.md,
  },
  comment: {
    alignItems: "flex-start",
    flexDirection: "row",
    gap: spacing.sm,
    marginBottom: spacing.md,
  },
  commentAvatar: {
    alignItems: "center",
    backgroundColor: colors.sageLight,
    borderRadius: 14,
    height: 28,
    justifyContent: "center",
    width: 28,
  },
  commentAvatarImage: { borderRadius: 14, height: 28, width: 28 },
  commentAvatarText: { color: colors.sageDark, fontFamily: typography.uiBold, fontSize: 11 },
  commentBubble: {
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 14,
    borderWidth: 1,
    flex: 1,
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm,
  },
  commentMeta: { alignItems: "center", flexDirection: "row", justifyContent: "space-between", gap: spacing.sm },
  commentAuthor: {
    color: colors.ink,
    fontFamily: typography.uiBold,
    fontSize: 11,
  },
  commentTime: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 10 },
  commentBody: {
    color: colors.ink,
    fontFamily: typography.ui,
    fontSize: 13,
    lineHeight: 19,
    marginTop: 2,
  },
  composer: {
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: "row",
    gap: spacing.sm,
    marginBottom: spacing.sm,
    marginTop: spacing.sm,
    paddingLeft: spacing.lg,
    paddingRight: spacing.xs,
    paddingVertical: spacing.xs,
    ...shadows.card,
  },
  input: {
    color: colors.ink,
    flex: 1,
    fontFamily: typography.ui,
    fontSize: 13,
    maxHeight: 100,
    minHeight: 36,
    paddingVertical: spacing.xs,
  },
  sendButton: {
    alignItems: "center",
    backgroundColor: colors.coral,
    borderRadius: 18,
    height: 36,
    justifyContent: "center",
    width: 36,
  },
  sendButtonDisabled: { opacity: 0.45 },
});
