import { StyleSheet } from "react-native";
import { colors, shadows, spacing, typography } from "@/styles/tokens";

export const homeStyles = StyleSheet.create({
  eyebrow: {
    color: colors.coralDark,
    fontFamily: typography.display,
    fontSize: 11,
    letterSpacing: 2,
  },
  title: {
    color: colors.ink,
    fontFamily: typography.display,
    fontSize: 29,
    marginTop: spacing.sm,
  },
  titleDecor: { fontSize: 24 },
  cta: {
    ...shadows.button,
    backgroundColor: colors.coral,
    borderRadius: 22,
    marginTop: spacing.xl,
    padding: spacing.xl,
  },
  ctaTitle: {
    color: colors.card,
    fontFamily: typography.display,
    fontSize: 20,
  },
  ctaBody: {
    color: colors.card,
    fontFamily: typography.ui,
    fontSize: 13,
    marginTop: spacing.sm,
    opacity: 0.9,
  },
  ctaAction: {
    color: colors.card,
    fontFamily: typography.uiBold,
    fontSize: 12,
    marginTop: spacing.lg,
  },
  error: { color: colors.coralDark, fontSize: 13, marginTop: spacing.md },
  loading: { alignItems: "center", minHeight: 180, justifyContent: "center" },
  statsRow: { flexDirection: "row", gap: spacing.sm, marginTop: spacing.lg },
  stat: {
    ...shadows.card,
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 16,
    borderWidth: 1,
    flex: 1,
    paddingHorizontal: spacing.sm,
    paddingVertical: spacing.md,
  },
  statValue: {
    color: colors.ink,
    fontFamily: typography.displayBold,
    fontSize: 20,
  },
  statLabel: {
    color: colors.inkSoft,
    fontFamily: typography.ui,
    fontSize: 10,
    marginTop: spacing.xs,
    textAlign: "center",
  },
  section: {
    color: colors.inkSoft,
    fontFamily: typography.uiBold,
    fontSize: 12,
    letterSpacing: 1,
    marginTop: spacing.xxl,
    textTransform: "uppercase",
  },
  card: {
    ...shadows.card,
    alignItems: "center",
    backgroundColor: colors.card,
    borderColor: colors.line,
    borderRadius: 22,
    borderWidth: 1,
    flexDirection: "row",
    marginTop: spacing.md,
    padding: spacing.lg,
  },
  cardEmoji: { fontSize: 30, marginRight: spacing.md },
  cardCopy: { flex: 1 },
  cardTitle: { color: colors.ink, fontFamily: typography.uiBold, fontSize: 15 },
  cardBody: {
    color: colors.inkSoft,
    fontFamily: typography.ui,
    fontSize: 12,
    marginTop: spacing.xs,
  },
  cardMeta: {
    color: colors.sageDark,
    fontFamily: typography.uiBold,
    fontSize: 11,
    marginTop: spacing.sm,
  },
  chevron: { color: colors.coralDark, fontSize: 28, fontWeight: "300" },
});
