import { StyleSheet } from 'react-native';
import { colors, shadows, typography } from '@/styles/tokens';

export const profileStyles = StyleSheet.create({
  eyebrow: { color: colors.coralDark, fontFamily: typography.display, fontSize: 11, letterSpacing: 2 },
  title: { color: colors.ink, fontFamily: typography.display, fontSize: 29, marginTop: 8 },
  body: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 14, lineHeight: 21, marginTop: 8 },
  profileHead: { alignItems: 'center', marginTop: 8 },
  avatar: { alignItems: 'center', backgroundColor: colors.coral, borderRadius: 38, height: 76, justifyContent: 'center', marginBottom: 10, width: 76 },
  avatarText: { color: colors.card, fontFamily: typography.displayBold, fontSize: 28 },
  profileName: { color: colors.ink, fontFamily: typography.display, fontSize: 20 },
  profileEmail: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 12, marginTop: 3 },
  editButton: { backgroundColor: colors.card, borderColor: colors.line, borderRadius: 999, borderWidth: 1, marginTop: 12, paddingHorizontal: 16, paddingVertical: 8 },
  editButtonText: { color: colors.coralDark, fontFamily: typography.uiBold, fontSize: 12 },
  card: { ...shadows.card, backgroundColor: colors.card, borderColor: colors.line, borderRadius: 18, borderWidth: 1, marginTop: 20, padding: 16 },
  label: { color: colors.inkSoft, fontFamily: typography.uiBold, fontSize: 11, letterSpacing: 1, marginBottom: 8, textTransform: 'uppercase' },
  labelSpaced: { color: colors.inkSoft, fontFamily: typography.uiBold, fontSize: 11, letterSpacing: 1, marginBottom: 8, marginTop: 14, textTransform: 'uppercase' },
  input: { borderColor: colors.line, borderRadius: 12, borderWidth: 1, color: colors.ink, fontSize: 15, paddingHorizontal: 12, paddingVertical: 11 },
  hint: { color: colors.inkSoft, fontSize: 11, lineHeight: 16, marginTop: 5 },
  save: { alignItems: 'center', backgroundColor: colors.coral, borderRadius: 13, marginTop: 14, minHeight: 46, justifyContent: 'center' },
  saveText: { color: colors.card, fontSize: 14, fontWeight: '800' },
  statsRow: { flexDirection: 'row', gap: 10, marginTop: 20 },
  stat: { alignItems: 'center', backgroundColor: colors.card, borderColor: colors.line, borderRadius: 16, borderWidth: 1, flex: 1, paddingHorizontal: 8, paddingVertical: 12 },
  statValue: { color: colors.ink, fontFamily: typography.displayBold, fontSize: 20 },
  statLabel: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 10, marginTop: 2, textAlign: 'center' },
  notice: { color: colors.sageDark, fontSize: 13, marginTop: 12 },
  error: { color: colors.coralDark, fontSize: 13, marginTop: 12 },
  settingsCard: { backgroundColor: colors.card, borderColor: colors.line, borderRadius: 18, borderWidth: 1, marginTop: 20, padding: 16 },
  settingsTitle: { color: colors.ink, fontFamily: typography.display, fontSize: 18, marginBottom: 14 },
  optionRow: { flexDirection: 'row', gap: 8 },
  option: { backgroundColor: colors.background, borderColor: colors.line, borderRadius: 12, borderWidth: 1, flex: 1, paddingVertical: 11, alignItems: 'center' },
  optionSelected: { backgroundColor: colors.sageLight, borderColor: colors.sage },
  optionText: { color: colors.inkSoft, fontSize: 13 },
  optionTextSelected: { color: colors.sageDark, fontWeight: '700' },
  settingRow: { alignItems: 'center', borderTopColor: colors.line, borderTopWidth: 1, flexDirection: 'row', justifyContent: 'space-between', marginTop: 16, paddingTop: 16 },
  settingIcon: { alignItems: 'center', backgroundColor: colors.background, borderRadius: 18, height: 36, justifyContent: 'center', marginRight: 10, width: 36 },
  settingCopy: { flex: 1, paddingRight: 12 },
  settingTitle: { color: colors.ink, fontSize: 14, fontWeight: '700' },
  chevron: { color: colors.inkSoft, fontSize: 24, fontWeight: '300' },
  danger: { alignItems: 'center', borderColor: colors.coralDark, borderRadius: 13, borderWidth: 1, marginTop: 24, minHeight: 46, justifyContent: 'center' },
  dangerText: { color: colors.coralDark, fontSize: 14, fontWeight: '800' },
  sheetBackdrop: { backgroundColor: 'rgba(51,38,46,0.35)', flex: 1, justifyContent: 'flex-end' },
  sheet: { backgroundColor: colors.background, borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: 24, paddingBottom: 34 },
  sheetHandle: { alignSelf: 'center', backgroundColor: colors.line, borderRadius: 4, height: 5, marginBottom: 18, width: 42 },
  sheetHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: 18 },
  sheetTitle: { color: colors.ink, fontFamily: typography.display, fontSize: 22 },
  sheetClose: { color: colors.inkSoft, fontSize: 30, fontWeight: '300', lineHeight: 30 },
});
