import { StyleSheet } from 'react-native';
import { colors, shadows, spacing, typography } from '@/styles/tokens';

export const writeStyles = StyleSheet.create({
  eyebrow: { color: colors.coralDark, fontFamily: typography.display, fontSize: 11, letterSpacing: 2 },
  title: { color: colors.ink, fontFamily: typography.display, fontSize: 29, marginTop: spacing.sm },
  subtitle: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 14, lineHeight: 21, marginTop: spacing.sm },
  error: { backgroundColor: '#FDE7E7', borderRadius: 12, color: colors.coralDark, marginTop: spacing.lg, padding: spacing.md },
  notice: { backgroundColor: colors.sageLight, borderRadius: 12, color: colors.sageDark, marginTop: spacing.lg, padding: spacing.md },
  statusLoading: { alignItems: 'center', minHeight: 220, justifyContent: 'center' },
  sealedCard: { ...shadows.card, alignItems: 'center', backgroundColor: colors.card, borderColor: colors.line, borderRadius: 24, borderWidth: 1, marginTop: spacing.xl, padding: spacing.xl },
  sealedIcon: { alignItems: 'center', backgroundColor: colors.sageLight, borderRadius: 32, height: 64, justifyContent: 'center', width: 64 },
  sealedTitle: { color: colors.ink, fontFamily: typography.display, fontSize: 22, marginTop: spacing.lg, textAlign: 'center' },
  sealedBody: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 13, lineHeight: 20, marginTop: spacing.sm, textAlign: 'center' },
  sealedMeta: { color: colors.sageDark, fontFamily: typography.uiBold, fontSize: 11, marginTop: spacing.md },
  sealedActions: { flexDirection: 'row', gap: spacing.sm, marginTop: spacing.lg, width: '100%' },
  sealedAction: { alignItems: 'center', borderRadius: 14, flex: 1, minHeight: 44, justifyContent: 'center', paddingHorizontal: spacing.sm },
  sealedActionSecondary: { backgroundColor: colors.sageLight },
  sealedActionDanger: { backgroundColor: '#FDE7E7' },
  sealedActionText: { color: colors.sageDark, fontFamily: typography.uiBold, fontSize: 12 },
  sealedActionDangerText: { color: colors.coralDark },
  editorModeHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.xl },
  editorModeTitle: { color: colors.ink, fontFamily: typography.uiBold, fontSize: 13 },
  cancelEdit: { alignItems: 'center', flexDirection: 'row', gap: spacing.xs, paddingHorizontal: spacing.xs, paddingVertical: spacing.xs },
  cancelEditText: { color: colors.inkSoft, fontFamily: typography.uiBold, fontSize: 12 },
  editor: { ...shadows.card, backgroundColor: colors.card, borderColor: colors.line, borderRadius: 20, borderWidth: 1, color: colors.ink, fontFamily: typography.ui, fontSize: 16, lineHeight: 24, marginTop: spacing.xl, minHeight: 180, padding: spacing.lg },
  counter: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 11, marginTop: spacing.xs, textAlign: 'right' },
  photoButton: { alignItems: 'center', backgroundColor: colors.card, borderColor: colors.line, borderRadius: 14, borderWidth: 1, marginTop: spacing.md, minHeight: 44, justifyContent: 'center' },
  photoButtonText: { color: colors.sageDark, fontFamily: typography.uiBold, fontSize: 13 },
  photoPreview: { borderRadius: 16, height: 180, overflow: 'hidden', width: 180 },
  photoPreviewImage: { height: '100%', width: '100%' },
  photoGallery: { marginTop: spacing.md },
  photoTile: { height: 180, marginRight: spacing.sm, position: 'relative', width: 180 },
  removePhoto: { alignItems: 'center', backgroundColor: 'rgba(51,38,46,0.78)', borderRadius: 14, height: 28, justifyContent: 'center', position: 'absolute', right: 8, top: 8, width: 28 },
  removePhotoText: { color: colors.card, fontSize: 22, fontWeight: '300', lineHeight: 24 },
  section: { color: colors.inkSoft, fontFamily: typography.uiBold, fontSize: 12, letterSpacing: 1, marginTop: spacing.xl, textTransform: 'uppercase' },
  moodRow: { alignItems: 'center', flexDirection: 'row', gap: spacing.sm, paddingRight: spacing.md },
  moodTile: { alignItems: 'center', backgroundColor: colors.cardWarm, borderColor: 'transparent', borderRadius: 25, borderWidth: 2, height: 50, justifyContent: 'center', width: 50 },
  moodTileSelected: { backgroundColor: colors.card, borderColor: colors.coral, ...shadows.card },
  moodAddTile: { alignItems: 'center', backgroundColor: colors.sageLight, borderColor: colors.sage, borderRadius: 25, borderWidth: 1, height: 50, justifyContent: 'center', width: 50 },
  moodEmoji: { fontSize: 24 },
  customMoodTileWrap: { height: 58, position: 'relative', width: 50 },
  removeCustomMood: { alignItems: 'center', backgroundColor: colors.coralDark, borderColor: colors.card, borderRadius: 9, borderWidth: 1, height: 18, justifyContent: 'center', position: 'absolute', right: -3, top: -2, width: 18 },
  sheetBackdrop: { backgroundColor: 'rgba(51,38,46,0.35)', flex: 1, justifyContent: 'flex-end' },
  sheet: { backgroundColor: colors.background, borderTopLeftRadius: 28, borderTopRightRadius: 28, padding: spacing.xl, paddingBottom: 34 },
  sheetHandle: { alignSelf: 'center', backgroundColor: colors.line, borderRadius: 999, height: 5, marginBottom: spacing.lg, width: 42 },
  sheetHeader: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginBottom: spacing.md },
  sheetTitle: { color: colors.ink, fontFamily: typography.display, fontSize: 22 },
  sheetClose: { alignItems: 'center', backgroundColor: colors.card, borderRadius: 18, height: 34, justifyContent: 'center', width: 34 },
  customMoodHint: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 13, lineHeight: 20, marginBottom: spacing.md },
  input: { backgroundColor: colors.card, borderColor: colors.line, borderRadius: 12, borderWidth: 1, color: colors.ink, fontFamily: typography.ui, fontSize: 20, paddingHorizontal: spacing.md, paddingVertical: spacing.md, textAlign: 'center' },
  primaryButton: { alignItems: 'center', backgroundColor: colors.coral, borderRadius: 14, marginTop: spacing.lg, minHeight: 48, justifyContent: 'center' },
  primaryButtonText: { color: colors.card, fontFamily: typography.uiBold, fontSize: 15 },
  prompt: { backgroundColor: colors.sageLight, borderRadius: 16, marginTop: spacing.md, padding: spacing.md },
  promptText: { color: colors.sageDark, fontFamily: typography.display, fontSize: 14, lineHeight: 20 },
  promptAction: { color: colors.sageDark, fontFamily: typography.uiBold, fontSize: 11, marginTop: spacing.sm },
  empty: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 14, marginTop: spacing.md },
  emptyCircleCard: { alignItems: 'center', backgroundColor: colors.cardWarm, borderColor: colors.line, borderRadius: 20, borderWidth: 1, marginTop: spacing.md, padding: spacing.lg },
  emptyCircleIcon: { alignItems: 'center', backgroundColor: colors.sageLight, borderRadius: 24, height: 48, justifyContent: 'center', width: 48 },
  emptyCircleTitle: { color: colors.ink, fontFamily: typography.uiBold, fontSize: 15, marginTop: spacing.md, textAlign: 'center' },
  emptyCircleBody: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 13, lineHeight: 19, marginTop: spacing.xs, textAlign: 'center' },
  emptyCircleButton: { alignItems: 'center', backgroundColor: colors.sageDark, borderRadius: 14, marginTop: spacing.md, minHeight: 44, justifyContent: 'center', paddingHorizontal: spacing.lg },
  emptyCircleButtonText: { color: colors.card, fontFamily: typography.uiBold, fontSize: 13 },
  sectionRow: { alignItems: 'center', flexDirection: 'row', justifyContent: 'space-between', marginTop: spacing.xl },
  sectionInRow: { marginTop: 0 },
  selectAll: { color: colors.sageDark, fontFamily: typography.uiBold, fontSize: 12 },
  circle: { alignItems: 'center', backgroundColor: colors.card, borderColor: colors.line, borderRadius: 16, borderWidth: 1, flexDirection: 'row', marginTop: spacing.sm, padding: spacing.md },
  circleSelected: { backgroundColor: colors.sageLight, borderColor: colors.sage },
  circleEmoji: { fontSize: 24, marginRight: spacing.md },
  circleCopy: { flex: 1 },
  circleName: { color: colors.ink, fontFamily: typography.uiSemiBold, fontSize: 15 },
  circleMeta: { color: colors.inkSoft, fontFamily: typography.ui, fontSize: 12, marginTop: 2 },
  check: { color: colors.sageDark, fontFamily: typography.uiSemiBold, fontSize: 24 },
  submit: { ...shadows.button, alignItems: 'center', backgroundColor: colors.coral, borderRadius: 18, justifyContent: 'center', marginTop: spacing.xl, minHeight: 54, padding: spacing.lg },
  submitPressed: { opacity: 0.85 },
  submitDisabled: { opacity: 0.6 },
  submitText: { color: colors.card, fontFamily: typography.uiBold, fontSize: 15 },
});
