import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type PropsWithChildren,
} from "react";
import {
  defaultSettings,
  readLocalSettings,
  writeLocalSettings,
  type Language,
  type LocalSettings,
} from "@/settings/settingsStorage";

const translations = {
  en: {
    home: "Home",
    write: "Write",
    circles: "Circles",
    profile: "Profile",
    hi: "Hi",
    yourProfile: "YOUR PROFILE",
    quietPlace: "A quiet place for you.",
    profileBody:
      "Your Google account is the only way into Bloom. We never show sealed writing here.",
    displayName: "Display name",
    timezone: "Device time zone",
    timezoneHint: "Follows your phone automatically",
    saveProfile: "Save profile",
    profileSaved: "Profile saved.",
    settings: "Settings",
    editProfile: "Edit profile",
    editProfileSubtitle: "Update your display name",
    language: "Language",
    chooseLanguage: "Choose your language",
    english: "English",
    chinese: "中文",
    reminder: "Daily reminder",
    reminderTime: "Reminder time",
    reminderHint: "Saved on this device for local reminders.",
    on: "On",
    off: "Off",
    done: "Done",
    cancel: "Cancel",
    entries: "Entries",
    bestStreak: "Best streak",
    pagesSealed: "Diaries sealed",
    activeCircles: "Active Circles",
    bloomed: "Bloomed",
    signOut: "Sign out",
    dangerZone: "Danger zone",
    dangerBody: "Deleting your account deactivates it and revokes your active sessions.",
    deleteAccount: "Delete account",
    todaysDiary: "TODAY'S DIARY",
    writeHonestly: "Write honestly.",
    diaryPrivate:
      "This diary entry stays private until the circles you choose bloom.",
    diaryPlaceholder: "What is alive for you today?",
    mood: "Mood (optional)",
    prompt: "A gentle prompt (optional)",
    promptSmallJoy: "What small thing made today feel lighter?",
    promptLearned: "What did today teach you about yourself?",
    promptFuture: "What do you hope your future self remembers?",
    sealTo: "Seal to circles",
    sealDiary: "Seal diary",
    attachPhoto: "Attach one photo (optional)",
    replacePhoto: "Replace photo",
    homeWrite: "Write today's diary",
    homeWriteBody: "Your next entry will stay sealed until bloom day.",
    openEditor: "Open the editor →",
    comingUp: "Coming up",
    readyToOpen: "Ready to open",
    noSealed: "No sealed circles yet",
    plantFirst: "Plant your first circle to begin.",
    yourGarden: "YOUR GARDEN",
    yourCircles: "Your circles",
    circlesSubtitle: "Small groups, sealed seasons, shared memories.",
    plantCircle: "Plant a circle",
    bloomAfter: "Bloom after",
    bloomDate: "Date",
    bloomTime: "Time",
    selectAll: "Select all",
    clearAll: "Clear all",
    activeCirclesTitle: "Active circles",
    invitations: "Invitations",
    joinQuestion: "Join this sealed circle?",
    join: "Join",
    decline: "Decline",
    morning: "GOOD MORNING",
    afternoon: "GOOD AFTERNOON",
    evening: "GOOD EVENING",
    joyful: "Joyful",
    calm: "Calm",
    heavy: "Heavy",
    restless: "Restless",
    radiant: "Radiant",
    moodAccessibility: "Mood",
    dismissNotice: "Dismiss notice",
    dismissError: "Dismiss error",
    continueWithGoogle: "Continue with Google",
    openingBloom: "Opening Bloom…",
    googleOnlyNote: "Your Google account is used only to sign in to Bloom.",
    welcomeTitle: "Write now. Read together later.",
    welcomeBody: "Keep a sealed daily diary with your closest people. Choose a bloom date, write freely, and open the whole season together.",
    timelineEyebrow: "THE BLOOM",
    timelineTitle: "Together, then.",
    timelineSubtitle: "Everything written in this circle is open now.",
    noSharedEntries: "No diary entries were shared in this circle.",
    reactWithHeart: "React with heart",
    comment: "comment",
    comments: "comments",
    commentPlaceholder: "Say something kind",
    post: "Post",
    diaryPhoto: "Diary photo",
    of: "of",
    openSharedTimeline: "Open shared timeline",
    back: "Back",
    backToCircles: "Back to circles",
    members: "Members",
    joined: "joined",
    fullyBloomed: "Fully bloomed",
    throughSeason: "through this season",
    inviteeEmail: "Invitee email",
    friendEmailPlaceholder: "friend@example.com",
    sending: "Sending…",
    inviteFriend: "Invite a friend",
    invitationSent: "Invitation sent.",
    leaveCircleTitle: "Leave this circle?",
    leaveCircleBody: "Your sealed diary entries stay private and will not be revealed to the remaining members.",
    keepCircle: "Keep circle",
    leaveCircle: "Leave circle",
    circleNotFound: "Circle not found.",
    circleName: "Circle name",
    circleNamePlaceholder: "e.g. The six-month season",
    createSealedCircle: "Create a sealed circle before writing.",
    noCirclesYet: "No circles yet. Plant one for your favorite people.",
    circleBlooms: "Blooms",
    sharedTimelineReady: "Your shared timeline is ready.",
    sealedStatus: "SEALED",
    bloomedStatus: "BLOOMED",
    member: "member",
    memberPlural: "members",
    restoreDraft: "Your unfinished diary was restored on this device.",
    writeBeforeSealing: "Write a few words before sealing today’s diary.",
    diarySealed: "Sealed. You can read this diary entry again when your circles bloom.",
    chooseSealedCircle: "Choose at least one sealed circle.",
    allowPhotoAccess: "Allow photo access to attach an image.",
    diaryEntry: "Diary entry",
    attachPhotoAccessibility: "Attach photos",
    selectedDiaryPhoto: "Selected diary photo",
    removePhoto: "Remove photo",
    choosePrompt: "Choose writing prompt",
    promptHint: "Tap for a gentle question to begin.",
    changePrompt: "Change prompt",
    choosePromptAction: "Choose prompt",
    selectCircle: "Select",
    sealDiaryEntry: "Seal diary entry",
    unknownSignInError: "Unknown sign-in error",
    signInFailed: "Google sign-in could not be completed.",
    missingIdentityToken: "Google did not return an identity token.",
    sessionStartFailed: "Bloom could not start your session",
    signInLoading: "Google sign-in is still loading.",
    circleLoadFailed: "Could not load circles.",
    gardenLoadFailed: "Could not load your garden.",
    statsLoadFailed: "Could not load your stats.",
    timelineLoadFailed: "Could not open this timeline.",
    reactionUpdateFailed: "Could not update your reaction.",
    commentsLoadFailed: "Could not load comments.",
    commentAddFailed: "Could not add your comment.",
    circleLoadDetailFailed: "Could not load this circle.",
    inviteFailed: "Could not send the invitation.",
    invitationUpdateFailed: "Could not update the invitation.",
    circleNameRequired: "Give your circle a name first.",
    circleCreateFailed: "Could not plant the circle.",
    leaveFailed: "Could not leave the circle.",
    profileSaveFailed: "Could not save your profile.",
    diarySealFailed: "Could not seal today’s diary.",
    openCircle: "Open circle",
    friend: "friend",
    deleteConfirmCancel: "Cancel",
    creatorRole: "Creator",
    memberRole: "Member",
  },
  zh: {
    home: "首页",
    write: "记录",
    circles: "圈子",
    profile: "我的",
    hi: "你好",
    yourProfile: "我的资料",
    quietPlace: "给自己留一处安静的地方。",
    profileBody:
      "Bloom 使用 Google 帐号登录，已封存的日记只有在开放日才能看见。",
    displayName: "显示名称",
    timezone: "设备时区",
    timezoneHint: "跟随手机自动更新",
    saveProfile: "保存资料",
    profileSaved: "资料已保存。",
    settings: "设置",
    editProfile: "编辑资料",
    editProfileSubtitle: "更新你的显示名称",
    language: "语言",
    chooseLanguage: "选择语言",
    english: "English",
    chinese: "中文",
    reminder: "每日提醒",
    reminderTime: "提醒时间",
    reminderHint: "保存在此设备，用于本地提醒。",
    on: "开启",
    off: "关闭",
    done: "完成",
    cancel: "取消",
    entries: "日记",
    bestStreak: "最佳连续记录",
    pagesSealed: "已封存日记",
    activeCircles: "进行中的圈子",
    bloomed: "已开放",
    signOut: "退出登录",
    dangerZone: "危险区域",
    dangerBody: "删除帐号会停用帐号并撤销所有登录会话。",
    deleteAccount: "删除帐号",
    todaysDiary: "今天的日记",
    writeHonestly: "诚实地写下来。",
    diaryPrivate: "这篇日记会一直保密，直到你选择的圈子开放。",
    diaryPlaceholder: "今天有什么想记录的？",
    mood: "心情（可选）",
    prompt: "温柔提示（可选）",
    promptSmallJoy: "今天有什么小事让你觉得轻松了一点？",
    promptLearned: "今天让你更了解自己什么？",
    promptFuture: "你希望未来的自己记住什么？",
    sealTo: "封存到圈子",
    sealDiary: "封存日记",
    attachPhoto: "添加一张照片（可选）",
    replacePhoto: "更换照片",
    homeWrite: "记录今天的日记",
    homeWriteBody: "下一篇日记会在开放日之前保持封存。",
    openEditor: "打开编辑器 →",
    comingUp: "即将开放",
    readyToOpen: "可以开放",
    noSealed: "还没有封存的圈子",
    plantFirst: "创建你的第一个圈子吧。",
    yourGarden: "我的花园",
    yourCircles: "我的圈子",
    circlesSubtitle: "小小的群组，封存的季节，共享的回忆。",
    plantCircle: "创建圈子",
    bloomAfter: "开放时间",
    bloomDate: "\u65e5\u671f",
    bloomTime: "\u65f6\u95f4",
    selectAll: "\u5168\u9009",
    clearAll: "\u6e05\u9664\u5168\u9009",
    activeCirclesTitle: "进行中的圈子",
    invitations: "邀请",
    joinQuestion: "加入这个封存圈子？",
    join: "加入",
    decline: "拒绝",
    morning: "早上好",
    afternoon: "下午好",
    evening: "晚上好",
    joyful: "喜悦",
    calm: "平静",
    heavy: "沉重",
    restless: "不安",
    radiant: "灿烂",
    moodAccessibility: "心情",
    dismissNotice: "关闭提示",
    dismissError: "关闭错误",
    continueWithGoogle: "使用 Google 继续",
    openingBloom: "正在打开 Bloom…",
    googleOnlyNote: "你的 Google 帐号仅用于登录 Bloom。",
    welcomeTitle: "现在写下，日后一起阅读。",
    welcomeBody: "和最亲近的人一起封存每日的日记。选择开放日期，自由书写，然后一起打开整个季节。",
    timelineEyebrow: "开放时刻",
    timelineTitle: "一起读，然后。",
    timelineSubtitle: "这个圈子里的所有日记现在都已开放。",
    noSharedEntries: "这个圈子还没有共享日记。",
    reactWithHeart: "用爱心回应",
    comment: "条评论",
    comments: "条评论",
    commentPlaceholder: "说些温柔的话",
    post: "发布",
    diaryPhoto: "日记照片",
    of: "/",
    openSharedTimeline: "打开共享时间线",
    back: "返回",
    backToCircles: "返回圈子",
    members: "成员",
    joined: "加入于",
    fullyBloomed: "已完全开放",
    throughSeason: "本季进度",
    inviteeEmail: "朋友的邮箱",
    friendEmailPlaceholder: "friend@example.com",
    sending: "发送中…",
    inviteFriend: "邀请朋友",
    invitationSent: "邀请已发送。",
    leaveCircleTitle: "要离开这个圈子吗？",
    leaveCircleBody: "你封存的日记会保持私密，不会向其他成员开放。",
    keepCircle: "留下",
    leaveCircle: "离开圈子",
    circleNotFound: "找不到这个圈子。",
    circleName: "圈子名称",
    circleNamePlaceholder: "例如：六个月的季节",
    createSealedCircle: "请先创建一个封存圈子。",
    noCirclesYet: "还没有圈子。为你珍惜的人创建一个吧。",
    circleBlooms: "开放于",
    sharedTimelineReady: "共享时间线已准备好。",
    sealedStatus: "封存中",
    bloomedStatus: "已开放",
    member: "位成员",
    memberPlural: "位成员",
    restoreDraft: "已从此设备恢复未完成的日记。",
    writeBeforeSealing: "请先写几句话，再封存今天的日记。",
    diarySealed: "已封存。圈子开放后，你可以再次阅读这篇日记。",
    chooseSealedCircle: "请至少选择一个封存圈子。",
    allowPhotoAccess: "请允许访问照片以添加图片。",
    diaryEntry: "日记内容",
    attachPhotoAccessibility: "添加照片",
    selectedDiaryPhoto: "已选择的日记照片",
    removePhoto: "移除照片",
    choosePrompt: "选择写作提示",
    promptHint: "点击一个温柔的问题开始吧。",
    changePrompt: "更换提示",
    choosePromptAction: "选择提示",
    selectCircle: "选择",
    sealDiaryEntry: "封存日记",
    unknownSignInError: "未知登录错误",
    signInFailed: "Google 登录未完成。",
    missingIdentityToken: "Google 没有返回身份令牌。",
    sessionStartFailed: "Bloom 无法开始你的会话",
    signInLoading: "Google 登录仍在加载。",
    circleLoadFailed: "无法加载圈子。",
    gardenLoadFailed: "无法加载你的花园。",
    statsLoadFailed: "无法加载你的统计数据。",
    timelineLoadFailed: "无法打开这个时间线。",
    reactionUpdateFailed: "无法更新回应。",
    commentsLoadFailed: "无法加载评论。",
    commentAddFailed: "无法添加评论。",
    circleLoadDetailFailed: "无法加载这个圈子。",
    inviteFailed: "无法发送邀请。",
    invitationUpdateFailed: "无法更新邀请。",
    circleNameRequired: "请先为圈子命名。",
    circleCreateFailed: "无法创建圈子。",
    leaveFailed: "无法离开圈子。",
    profileSaveFailed: "无法保存资料。",
    diarySealFailed: "无法封存今天的日记。",
    openCircle: "打开圈子",
    friend: "朋友",
    deleteConfirmCancel: "取消",
    creatorRole: "创建者",
    memberRole: "成员",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;
type SettingsContextValue = LocalSettings & {
  isReady: boolean;
  setLanguage: (language: Language) => void;
  setRemindersEnabled: (enabled: boolean) => void;
  setReminderTime: (time: string) => void;
  t: (key: TranslationKey) => string;
};

const SettingsContext = createContext<SettingsContextValue | null>(null);

export function SettingsProvider({ children }: PropsWithChildren) {
  const [settings, setSettings] = useState<LocalSettings>(defaultSettings);
  const [isReady, setIsReady] = useState(false);

  useEffect(() => {
    void readLocalSettings().then((stored) => {
      setSettings(stored);
      setIsReady(true);
    });
  }, []);

  useEffect(() => {
    if (isReady) void writeLocalSettings(settings);
  }, [isReady, settings]);
  const update = useCallback(
    (change: Partial<LocalSettings>) =>
      setSettings((current) => ({ ...current, ...change })),
    [],
  );
  const value = useMemo<SettingsContextValue>(
    () => ({
      ...settings,
      isReady,
      setLanguage: (language) => update({ language }),
      setRemindersEnabled: (remindersEnabled) => update({ remindersEnabled }),
      setReminderTime: (reminderTime) => update({ reminderTime }),
      t: (key) => translations[settings.language][key],
    }),
    [isReady, settings, update],
  );
  return (
    <SettingsContext.Provider value={value}>
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings(): SettingsContextValue {
  const context = useContext(SettingsContext);
  if (!context)
    throw new Error("useSettings must be used inside SettingsProvider");
  return context;
}
