import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useMemo,
  useState,
  type PropsWithChildren,
} from "react";
import {
  defaultSettings,
  readLocalSettings,
  writeLocalSettings,
  type Language,
  type LocalSettings,
} from "@/settings/settingsStorage";
import {
  configureNotificationPresentation,
  syncDailyReminder,
  type ReminderSyncResult,
} from "@/notifications/reminderNotifications";

const translations = {
  en: {
    home: "Home",
    write: "Write",
    circles: "Circles",
    profile: "Profile",
    hi: "Hi",
    yourProfile: "YOUR PROFILE",
    quietPlace: "A quiet place for you.",
    displayName: "Display name",
    timezone: "Device time zone",
    timezoneHint: "Follows your phone automatically",
    saveProfile: "Save profile",
    profileSaved: "Profile saved.",
    settings: "Settings",
    editProfile: "Edit profile",
    editProfileSubtitle: "Update your display name",
    diaryCalendar: "Diary calendar",
    diaryCalendarSubtitle: "See your writing rhythm month by month",
    archivedCircles: "Archived circles",
    archivedCirclesSubtitle: "Bloomed circles you archive remain here so you can revisit every post.",
    language: "Language",
    chooseLanguage: "Choose your language",
    english: "English",
    chinese: "中文",
    reminder: "Daily reminder",
    reminderTime: "Reminder time",
    reminderHint: "Saved on this device for local reminders.",
    reminderPermissionDenied:
      "Notifications are disabled. Enable them in your phone settings to receive daily reminders.",
    reminderTimeInvalid: "Choose a reminder time in HH:MM format.",
    on: "On",
    off: "Off",
    done: "Done",
    cancel: "Cancel",
    entries: "Entries",
    bestStreak: "Best streak",
    pagesSealed: "Diaries sealed",
    activeCircles: "Active Circles",
    bloomed: "Bloomed",
    signOut: "Sign out",
    dangerZone: "Danger zone",
    dangerBody:
      "Deleting your account deactivates it and revokes your active sessions.",
    deleteAccount: "Delete account",
    todaysDiary: "TODAY'S DIARY",
    writeHonestly: "Write honestly.",
    diaryPrivate:
      "This diary entry stays private until the circles you choose bloom.",
    diaryPlaceholder: "What is alive for you today?",
    mood: "Mood (optional)",
    prompt: "A gentle prompt (optional)",
    promptSmallJoy: "What small thing made today feel lighter?",
    promptLearned: "What did today teach you about yourself?",
    promptFuture: "What do you hope your future self remembers?",
    sealTo: "Seal to circles",
    sealDiary: "Seal diary",
    attachPhoto: "Attach photos (optional)",
    addMorePhotos: "Add more photos",
    replacePhoto: "Replace photo",
    homeWrite: "Write today's diary",
    homeWriteBody: "Your next entry will stay sealed until bloom day.",
    openEditor: "Open the editor →",
    comingUp: "Coming up",
    readyToOpen: "Ready to open",
    noSealed: "No sealed circles yet",
    noSealedCirclesTitle: "Your diary needs a circle",
    createCircleAction: "Create a circle",
    plantFirst: "Plant your first circle to begin.",
    yourGarden: "YOUR GARDEN",
    yourCircles: "Your circles",
    circlesSubtitle: "Small groups, sealed seasons, shared memories.",
    plantCircle: "Plant a circle",
    bloomAfter: "Bloom after",
    bloomDate: "Date",
    bloomTime: "Time",
    selectAll: "Select all",
    clearAll: "Clear all",
    activeCirclesTitle: "Active circles",
    invitations: "Invitations",
    joinQuestion: "Join this sealed circle?",
    join: "Join",
    decline: "Decline",
    morning: "GOOD MORNING",
    afternoon: "GOOD AFTERNOON",
    evening: "GOOD EVENING",
    joyful: "Joyful",
    calm: "Calm",
    heavy: "Heavy",
    restless: "Restless",
    radiant: "Radiant",
    angry: "Angry",
    anxious: "Anxious",
    tired: "Tired",
    grateful: "Grateful",
    loved: "Loved",
    focused: "Focused",
    frustrated: "Frustrated",
    addCustomMood: "Add a mood",
    removeCustomMood: "Remove custom mood",
    customMood: "Your own mood",
    customMoodHint: "Choose an emoji from your keyboard, like the LINE emoji you use with friends.",
    customMoodPlaceholder: "Type an emoji",
    customMoodRequired: "Add an emoji before saving.",
    customMoodInvalid: "Use one emoji without the | character.",
    customMoodTooLong: "Keep your custom mood to 8 characters or fewer.",
    saveMood: "Use this mood",
    moodAccessibility: "Mood",
    dismissNotice: "Dismiss notice",
    dismissError: "Dismiss error",
    continueWithGoogle: "Continue with Google",
    openingBloom: "Opening Bloom…",
    googleOnlyNote: "Your Google account is used only to sign in to Bloom.",
    welcomeTitle: "Write now. Read together later.",
    welcomeBody:
      "Keep a sealed daily diary with your closest people. Choose a bloom date, write freely, and open the whole season together.",
    timelineEyebrow: "THE BLOOM",
    timelineTitle: "Together, then.",
    timelineSubtitle: "Everything written in this circle is open now.",
    filter: "Filter",
    filterByDate: "By date",
    filterByPerson: "By person",
    anyDate: "Any date",
    everyone: "Everyone",
    person: "Person",
    applyFilters: "Apply filters",
    resetFilters: "Reset",
    loadingMore: "Loading more diaries…",
    timelineEnd: "You've reached the end of this bloom.",
    entryDetail: "Diary entry",
    backToTimeline: "Back to timeline",
    commentsTitle: "Comments",
    noComments: "No comments yet. Be the first to say something kind.",
    felt: "felt",
    openDiaryEntry: "Open diary entry",
    noSharedEntries: "No diary entries were shared in this circle.",
    reactWithHeart: "React with heart",
    comment: "comment",
    comments: "comments",
    commentPlaceholder: "Say something kind",
    post: "Post",
    diaryPhoto: "Diary photo",
    of: "of",
    openSharedTimeline: "Open shared timeline",
    back: "Back",
    backToCircles: "Back to circles",
    members: "Members",
    joined: "joined",
    fullyBloomed: "Fully bloomed",
    throughSeason: "through this season",
    inviteeEmail: "Invitee email",
    friendEmailPlaceholder: "friend@example.com",
    sending: "Sending…",
    inviteFriend: "Invite a friend",
    invitationSent: "Invitation sent.",
    leaveCircleTitle: "Leave this circle?",
    leaveCircleBody:
      "Your sealed diary entries stay private and will not be revealed to the remaining members.",
    keepCircle: "Keep circle",
    leaveCircle: "Leave circle",
    circleNotFound: "Circle not found.",
    circleName: "Circle name",
    circleNamePlaceholder: "e.g. The six-month season",
    circleEmoji: "Circle emoji",
    editCircle: "Edit circle",
    saveCircle: "Save circle",
    deleteCircle: "Delete circle",
    deleteCircleTitle: "Delete this circle?",
    deleteCircleBody:
      "Empty circles are permanently deleted. Circles with diary publications are archived and their sealed publications are withdrawn.",
    deleteCircleConfirmName: "Type the circle name to confirm",
    circleDeleted: "Circle deleted.",
    circleArchived: "Circle archived.",
    circleRestored: "Circle restored to your active list.",
    circleRestoreFailed: "The circle could not be restored.",
    restoreCircle: "Restore circle",
    removeMember: "Remove",
    removeMemberTitle: "Remove this member?",
    removeMemberBody: "{name} will leave this circle and their sealed diary entry will be withdrawn.",
    removeMemberFailed: "The member could not be removed.",
    archiveCircle: "Archive",
    archiveCircleTitle: "Archive this circle?",
    archiveCircleBody: "The circle will move to your Archived circles. You can still view every post and reply; other members will see it normally.",
    circleSaved: "Circle details saved.",
    circleEditLocked: "A bloomed circle can no longer be edited.",
    circleOverview: "Circle overview",
    circleTimezone: "Time zone",
    createSealedCircle: "Create a sealed circle before writing.",
    noCirclesYet: "No circles yet. Plant one for your favorite people.",
    circleBlooms: "Blooms",
    sharedTimelineReady: "Your shared timeline is ready.",
    sealedStatus: "SEALED",
    bloomedStatus: "BLOOMED",
    member: "member",
    memberPlural: "members",
    restoreDraft: "Your unfinished diary was restored on this device.",
    writeBeforeSealing: "Write a few words before sealing today’s diary.",
    diarySealed:
      "Sealed. You can read this diary entry again when your circles bloom.",
    todaySealedTitle: "Today's diary is sealed",
    todaySealedBody:
      "You've already sealed today's diary. Come back tomorrow to write again.",
    todayEditableBody:
      "You can update or delete this diary until your local midnight.",
    todayLockedBody:
      "This diary can no longer be changed because today’s edit window is closed.",
    editToday: "Edit today's diary",
    deleteToday: "Delete today's diary",
    deleteTodayTitle: "Delete today's diary?",
    deleteTodayBody:
      "This removes today's diary from its circles. You can write a replacement before midnight.",
    todayDeleted: "Today's diary was deleted.",
    todayUpdated: "Today's diary was updated.",
    saveChanges: "Save changes",
    todayEditUntil: "Editable until",
    todayAlreadySealed: "Today's diary is already sealed.",
    todayStatusLoadFailed: "Could not check today's diary status.",
    chooseSealedCircle: "Choose at least one sealed circle.",
    allowPhotoAccess: "Allow photo access to attach an image.",
    changeAvatar: "Change profile photo",
    avatarSaved: "Profile photo updated.",
    avatarSaveFailed: "The profile photo could not be updated.",
    friends: "Friends",
    friendsRecorded: "friends saved",
    lastConnected: "Last connected",
    noFriendsYet: "Friends you invite or join with will appear here.",
    photoProcessingFailed: "That image could not be prepared. Please choose another photo.",
    diaryEntry: "Diary entry",
    attachPhotoAccessibility: "Attach photos",
    selectedDiaryPhoto: "Selected diary photo",
    removePhoto: "Remove photo",
    choosePrompt: "Choose writing prompt",
    promptHint: "Tap for a gentle question to begin.",
    changePrompt: "Change prompt",
    choosePromptAction: "Choose prompt",
    selectCircle: "Select",
    sealDiaryEntry: "Seal diary entry",
    unknownSignInError: "Unknown sign-in error",
    signInFailed: "Google sign-in could not be completed.",
    googleNotConfigured:
      "Google sign-in is not configured in this build. Please install the latest Bloom release.",
    missingIdentityToken: "Google did not return an identity token.",
    sessionStartFailed: "Bloom could not start your session",
    signInLoading: "Google sign-in is still loading.",
    circleLoadFailed: "Could not load circles.",
    gardenLoadFailed: "Could not load your garden.",
    statsLoadFailed: "Could not load your stats.",
    timelineLoadFailed: "Could not open this timeline.",
    entryLoadFailed: "Could not open this diary entry.",
    reactionUpdateFailed: "Could not update your reaction.",
    commentsLoadFailed: "Could not load comments.",
    commentAddFailed: "Could not add your comment.",
    commentDeleteFailed: "Could not delete your comment.",
    deleteComment: "Delete comment",
    deleteCommentTitle: "Delete this comment?",
    deleteCommentBody: "This comment will be removed permanently.",
    commentDeleted: "Comment deleted.",
    circleLoadDetailFailed: "Could not load this circle.",
    inviteFailed: "Could not send the invitation.",
    invitationUpdateFailed: "Could not update the invitation.",
    circleNameRequired: "Give your circle a name first.",
    circleCreateFailed: "Could not plant the circle.",
    circleSaveFailed: "Could not save circle details.",
    leaveFailed: "Could not leave the circle.",
    profileSaveFailed: "Could not save your profile.",
    diarySealFailed: "Could not seal today’s diary.",
    requestFailed: "Bloom could not complete that request. Please try again.",
    openCircle: "Open circle",
    friend: "friend",
    deleteConfirmCancel: "Cancel",
    creatorRole: "Creator",
    memberRole: "Member",
    closePhotoViewer: "Close photo viewer",
    backToProfile: "Back to profile",
    noArchivedCircles: "No archived circles",
    noArchivedCirclesBody: "Bloomed circles you archive will appear here.",
    openArchivedCircle: "Open archived circle",
    archivedStatus: "ARCHIVED",
    scheduledBloom: "Scheduled bloom",
    archivedReadOnly: "This circle is archived. Its timeline is still available for viewing and replies.",
    personalArchivedReadOnly: "This circle is archived only in your view. You can still view and reply to every post.",
    calendarTitle: "Diary calendar",
    calendarSubtitle: "A gentle view of the days you showed up.",
    today: "Today",
    previousMonth: "Previous month",
    nextMonth: "Next month",
    diaryWritten: "Diary written",
    noDiaryOnDay: "No diary recorded on this day.",
    futureDiaryDay: "This day has not arrived yet.",
    sealedToCircleCount: "Sealed to {count} circle(s)",
    calendarLoadFailed: "Could not load your diary calendar.",
  },
  zh: {
    home: "首页",
    write: "记录",
    circles: "圈子",
    profile: "我的",
    hi: "你好",
    yourProfile: "我的资料",
    quietPlace: "给自己留一处安静的地方。",
    displayName: "显示名称",
    timezone: "设备时区",
    timezoneHint: "跟随手机自动更新",
    saveProfile: "保存资料",
    profileSaved: "资料已保存。",
    settings: "设置",
    editProfile: "编辑资料",
    editProfileSubtitle: "更新你的显示名称",
    diaryCalendar: "日记日历",
    diaryCalendarSubtitle: "按月份查看你的记录节奏",
    archivedCircles: "已归档圈子",
    archivedCirclesSubtitle: "你归档的已开放圈子会保留在这里，方便查看所有帖子。",
    language: "语言",
    chooseLanguage: "选择语言",
    english: "English",
    chinese: "中文",
    reminder: "每日提醒",
    reminderTime: "提醒时间",
    reminderHint: "保存在此设备，用于本地提醒。",
    reminderPermissionDenied:
      "通知已关闭。请在手机设置中开启通知，以接收每日提醒。",
    reminderTimeInvalid: "请使用 HH:MM 格式设置提醒时间。",
    on: "开启",
    off: "关闭",
    done: "完成",
    cancel: "取消",
    entries: "日记",
    bestStreak: "最佳连续记录",
    pagesSealed: "已封存日记",
    activeCircles: "进行中的圈子",
    bloomed: "已开放",
    signOut: "退出登录",
    dangerZone: "危险区域",
    dangerBody: "删除帐号会停用帐号并撤销所有登录会话。",
    deleteAccount: "删除帐号",
    todaysDiary: "今天的日记",
    writeHonestly: "诚实地写下来。",
    diaryPrivate: "这篇日记会一直保密，直到你选择的圈子开放。",
    diaryPlaceholder: "今天有什么想记录的？",
    mood: "心情（可选）",
    prompt: "温柔提示（可选）",
    promptSmallJoy: "今天有什么小事让你觉得轻松了一点？",
    promptLearned: "今天让你更了解自己什么？",
    promptFuture: "你希望未来的自己记住什么？",
    sealTo: "封存到圈子",
    sealDiary: "封存日记",
    attachPhoto: "添加照片（可选）",
    addMorePhotos: "添加更多照片",
    replacePhoto: "更换照片",
    homeWrite: "记录今天的日记",
    homeWriteBody: "下一篇日记会在开放日之前保持封存。",
    openEditor: "打开编辑器 →",
    comingUp: "即将开放",
    readyToOpen: "可以开放",
    noSealed: "还没有封存的圈子",
    noSealedCirclesTitle: "你的日记需要一个圈子",
    createCircleAction: "创建圈子",
    plantFirst: "创建你的第一个圈子吧。",
    yourGarden: "我的花园",
    yourCircles: "我的圈子",
    circlesSubtitle: "小小的群组，封存的季节，共享的回忆。",
    plantCircle: "创建圈子",
    bloomAfter: "开放时间",
    bloomDate: "\u65e5\u671f",
    bloomTime: "\u65f6\u95f4",
    selectAll: "\u5168\u9009",
    clearAll: "\u6e05\u9664\u5168\u9009",
    activeCirclesTitle: "进行中的圈子",
    invitations: "邀请",
    joinQuestion: "加入这个封存圈子？",
    join: "加入",
    decline: "拒绝",
    morning: "早上好",
    afternoon: "下午好",
    evening: "晚上好",
    joyful: "喜悦",
    calm: "平静",
    heavy: "沉重",
    restless: "不安",
    radiant: "灿烂",
    angry: "生气",
    anxious: "焦虑",
    tired: "疲惫",
    grateful: "感恩",
    loved: "被爱",
    focused: "专注",
    frustrated: "挫败",
    addCustomMood: "添加心情",
    removeCustomMood: "删除自定义心情",
    customMood: "自定义心情",
    customMoodHint: "从键盘选择一个表情，例如你和朋友聊天时使用的 LINE 表情。",
    customMoodPlaceholder: "输入一个表情",
    customMoodRequired: "请先添加表情再保存。",
    customMoodInvalid: "请使用一个不含 | 符号的表情。",
    customMoodTooLong: "自定义心情最多 8 个字符。",
    saveMood: "使用这个心情",
    moodAccessibility: "心情",
    dismissNotice: "关闭提示",
    dismissError: "关闭错误",
    continueWithGoogle: "使用 Google 继续",
    openingBloom: "正在打开 Bloom…",
    googleOnlyNote: "你的 Google 帐号仅用于登录 Bloom。",
    welcomeTitle: "现在写下，日后一起阅读。",
    welcomeBody:
      "和最亲近的人一起封存每日的日记。选择开放日期，自由书写，然后一起打开整个季节。",
    timelineEyebrow: "开放时刻",
    timelineTitle: "一起读，然后。",
    timelineSubtitle: "这个圈子里的所有日记现在都已开放。",
    loadingMore: "正在加载更多日记……",
    timelineEnd: "你已经看到这次开放的全部内容了。",
    entryDetail: "日记内容",
    backToTimeline: "返回时间线",
    commentsTitle: "评论",
    noComments: "还没有评论。第一个说些温柔的话吧。",
    felt: "心情",
    openDiaryEntry: "打开日记内容",
    noSharedEntries: "这个圈子还没有共享日记。",
    reactWithHeart: "用爱心回应",
    comment: "条评论",
    comments: "条评论",
    commentPlaceholder: "说些温柔的话",
    post: "发布",
    diaryPhoto: "日记照片",
    of: "/",
    openSharedTimeline: "打开共享时间线",
    back: "返回",
    backToCircles: "返回圈子",
    members: "成员",
    joined: "加入于",
    fullyBloomed: "已完全开放",
    throughSeason: "本季进度",
    inviteeEmail: "朋友的邮箱",
    friendEmailPlaceholder: "friend@example.com",
    sending: "发送中…",
    inviteFriend: "邀请朋友",
    invitationSent: "邀请已发送。",
    leaveCircleTitle: "要离开这个圈子吗？",
    leaveCircleBody: "你封存的日记会保持私密，不会向其他成员开放。",
    keepCircle: "留下",
    leaveCircle: "离开圈子",
    circleNotFound: "找不到这个圈子。",
    circleName: "圈子名称",
    circleNamePlaceholder: "例如：六个月的季节",
    circleEmoji: "圈子表情",
    editCircle: "编辑圈子",
    saveCircle: "保存圈子",
    deleteCircle: "删除圈子",
    deleteCircleTitle: "删除这个圈子？",
    deleteCircleBody:
      "空圈子会被永久删除。已有日记的圈子会被归档，封存的发布内容会被撤回。",
    deleteCircleConfirmName: "输入圈子名称以确认",
    circleDeleted: "圈子已删除。",
    circleArchived: "圈子已归档。",
    circleRestored: "圈子已恢复到你的活跃列表。",
    circleRestoreFailed: "无法恢复这个圈子。",
    restoreCircle: "恢复圈子",
    removeMember: "移除",
    removeMemberTitle: "要移除这位成员吗？",
    removeMemberBody: "{name} 将离开这个圈子，其封存日记也会被撤回。",
    removeMemberFailed: "无法移除这位成员。",
    archiveCircle: "归档",
    archiveCircleTitle: "要归档这个圈子吗？",
    archiveCircleBody: "这个圈子会移到你的已归档圈子。你仍可查看所有帖子并回复，其他成员仍会正常看到它。",
    circleSaved: "圈子信息已保存。",
    circleEditLocked: "圈子开放后无法再编辑。",
    circleOverview: "圈子概览",
    circleTimezone: "时区",
    createSealedCircle: "请先创建一个封存圈子。",
    noCirclesYet: "还没有圈子。为你珍惜的人创建一个吧。",
    circleBlooms: "开放于",
    sharedTimelineReady: "共享时间线已准备好。",
    sealedStatus: "封存中",
    bloomedStatus: "已开放",
    member: "位成员",
    memberPlural: "位成员",
    restoreDraft: "已从此设备恢复未完成的日记。",
    writeBeforeSealing: "请先写几句话，再封存今天的日记。",
    diarySealed: "已封存。圈子开放后，你可以再次阅读这篇日记。",
    todaySealedTitle: "今天的日记已封存",
    todaySealedBody: "你今天已经完成日记封存。明天再回来继续记录吧。",
    todayEditableBody: "在本地零点前，你可以更新或删除这篇日记。",
    todayLockedBody: "今天的编辑时间已结束，这篇日记无法再更改。",
    editToday: "编辑今天的日记",
    deleteToday: "删除今天的日记",
    deleteTodayTitle: "删除今天的日记？",
    deleteTodayBody: "这会从圈子中移除今天的日记。在零点前你仍可以重新写一篇。",
    todayDeleted: "今天的日记已删除。",
    todayUpdated: "今天的日记已更新。",
    saveChanges: "保存更改",
    todayEditUntil: "可编辑至",
    todayAlreadySealed: "今天的日记已经封存。",
    todayStatusLoadFailed: "无法检查今天的日记状态。",
    chooseSealedCircle: "请至少选择一个封存圈子。",
    allowPhotoAccess: "请允许访问照片以添加图片。",
    changeAvatar: "更换头像",
    avatarSaved: "头像已更新。",
    avatarSaveFailed: "头像更新失败。",
    friends: "朋友",
    friendsRecorded: "位朋友已记录",
    lastConnected: "最近联系",
    noFriendsYet: "你邀请或一起加入圈子的朋友会显示在这里。",
    diaryEntry: "日记内容",
    attachPhotoAccessibility: "添加照片",
    selectedDiaryPhoto: "已选择的日记照片",
    removePhoto: "移除照片",
    choosePrompt: "选择写作提示",
    promptHint: "点击一个温柔的问题开始吧。",
    changePrompt: "更换提示",
    choosePromptAction: "选择提示",
    selectCircle: "选择",
    sealDiaryEntry: "封存日记",
    unknownSignInError: "未知登录错误",
    signInFailed: "Google 登录未完成。",
    googleNotConfigured: "此版本尚未配置 Google 登录，请安装最新的 Bloom 版本。",
    missingIdentityToken: "Google 没有返回身份令牌。",
    sessionStartFailed: "Bloom 无法开始你的会话",
    signInLoading: "Google 登录仍在加载。",
    circleLoadFailed: "无法加载圈子。",
    gardenLoadFailed: "无法加载你的花园。",
    statsLoadFailed: "无法加载你的统计数据。",
    timelineLoadFailed: "无法打开这个时间线。",
    entryLoadFailed: "无法打开这篇日记。",
    reactionUpdateFailed: "无法更新回应。",
    commentsLoadFailed: "无法加载评论。",
    commentAddFailed: "无法添加评论。",
    commentDeleteFailed: "无法删除评论。",
    deleteComment: "删除评论",
    deleteCommentTitle: "删除这条评论？",
    deleteCommentBody: "这条评论将被永久移除。",
    commentDeleted: "评论已删除。",
    circleLoadDetailFailed: "无法加载这个圈子。",
    inviteFailed: "无法发送邀请。",
    invitationUpdateFailed: "无法更新邀请。",
    circleNameRequired: "请先为圈子命名。",
    circleCreateFailed: "无法创建圈子。",
    circleSaveFailed: "无法保存圈子信息。",
    leaveFailed: "无法离开圈子。",
    profileSaveFailed: "无法保存资料。",
    diarySealFailed: "无法封存今天的日记。",
    requestFailed: "Bloom 无法完成该请求，请稍后再试。",
    photoProcessingFailed: "无法处理该图片，请选择其他照片。",
    openCircle: "打开圈子",
    friend: "朋友",
    deleteConfirmCancel: "取消",
    creatorRole: "创建者",
    memberRole: "成员",
    filter: "筛选",
    filterByDate: "按日期",
    filterByPerson: "按成员",
    anyDate: "所有日期",
    everyone: "所有成员",
    person: "成员",
    applyFilters: "应用筛选",
    resetFilters: "重置",
    closePhotoViewer: "关闭照片浏览器",
    backToProfile: "返回我的",
    noArchivedCircles: "没有已归档圈子",
    noArchivedCirclesBody: "你归档的已开放圈子会显示在这里。",
    openArchivedCircle: "打开已归档圈子",
    archivedStatus: "已归档",
    scheduledBloom: "原定开放时间",
    archivedReadOnly: "这个圈子已归档，你仍然可以查看时间线并回复。",
    personalArchivedReadOnly: "这个圈子只在你的页面归档，你仍然可以查看和回复所有帖子。",
    calendarTitle: "日记日历",
    calendarSubtitle: "温柔地回看你认真记录的每一天。",
    today: "今天",
    previousMonth: "上个月",
    nextMonth: "下个月",
    diaryWritten: "已写日记",
    noDiaryOnDay: "这一天没有记录日记。",
    futureDiaryDay: "这一天还没有到来。",
    sealedToCircleCount: "已封存到 {count} 个圈子",
    calendarLoadFailed: "无法加载日记日历。",
  },
} as const;

export type TranslationKey = keyof typeof translations.en;
type SettingsContextValue = LocalSettings & {
  isReady: boolean;
  setLanguage: (language: Language) => void;
  setRemindersEnabled: (enabled: boolean) => void;
  setReminderTime: (time: string) => void;
  addCustomMood: (mood: string) => void;
  removeCustomMood: (mood: string) => void;
  reminderStatus: ReminderSyncResult | "idle";
  t: (key: TranslationKey) => string;
};

const SettingsContext = createContext<SettingsContextValue | null>(null);

export function SettingsProvider({ children }: PropsWithChildren) {
  const [settings, setSettings] = useState<LocalSettings>(defaultSettings);
  const [isReady, setIsReady] = useState(false);
  const [reminderStatus, setReminderStatus] = useState<
    ReminderSyncResult | "idle"
  >("idle");

  useEffect(() => {
    void readLocalSettings().then((stored) => {
      setSettings(stored);
      setIsReady(true);
    });
  }, []);

  useEffect(() => {
    if (!isReady) return;
    void writeLocalSettings(settings);
    const timeout = setTimeout(() => {
      void syncDailyReminder(settings).then(setReminderStatus);
    }, 250);
    return () => clearTimeout(timeout);
  }, [isReady, settings]);

  useEffect(() => {
    configureNotificationPresentation();
  }, []);
  const update = useCallback(
    (change: Partial<LocalSettings>) =>
      setSettings((current) => ({ ...current, ...change })),
    [],
  );
  const value = useMemo<SettingsContextValue>(
    () => ({
      ...settings,
      isReady,
      setLanguage: (language) => update({ language }),
      setRemindersEnabled: (remindersEnabled) => update({ remindersEnabled }),
      setReminderTime: (reminderTime) => update({ reminderTime }),
      addCustomMood: (mood) => update({
        customMoods: [...new Set([...settings.customMoods, mood.trim()])].slice(0, 20),
      }),
      removeCustomMood: (mood) => update({
        customMoods: settings.customMoods.filter((item) => item !== mood),
      }),
      reminderStatus,
      t: (key) => translations[settings.language][key],
    }),
    [isReady, reminderStatus, settings, update],
  );
  return (
    <SettingsContext.Provider value={value}>
      {children}
    </SettingsContext.Provider>
  );
}

export function useSettings(): SettingsContextValue {
  const context = useContext(SettingsContext);
  if (!context)
    throw new Error("useSettings must be used inside SettingsProvider");
  return context;
}
